### ISSUE TITLE
 7-3 (d), How the last two lines work?

### ISSUE THREAD

**Issue by baoyuxu** [CyberZHG/CLRS-Solution#13]
The equation became smaller rather than magnified.

**Comment by CyberZHG** [comment]
I've updated the solution, see if it is more reasonable to you?

**Comment by baoyuxu** [comment]
That`s works.THX

**Comment by baoyuxu** [comment]
7-5 c, this  time.
About the convertion from sum to integral, it is not the same as inequation A.11 && A.12.

**Comment by baoyuxu** [comment]
![screenshot from 2018-05-17 13-57-51_meitu_2](https://user-images.githubusercontent.com/18047650/40159241-e5c00856-59da-11e8-94f1-d6455740d692.jpg)
maybe like this?

**Comment by CyberZHG** [comment]
Note that it is not a __*monotonic*__ function and we don't know whether n is divisible by 3.
